### ISSUE TITLE
Antenna Mast

### ISSUE THREAD

**Issue by doebrowsk** [doebrowsk/tank-chair#4]
With the removal of the current overhead mast on Jenks, we will need to attach a new one that will allow elevation of the antenna for emergency stop (and later gps). We will need a solution that hopefully will be easy to remove and move, likely involving the already existing rails on the Jenks frame.

The solution to this problem should be documented, with an explanation on why it was chosen. Pictures may also be helpful here.

**Comment by canoe12** [comment]
i got this one too

**Comment by canoe12** [comment]
made a piece that pivots so you can put it up or take it down pretty easily
